GET http://localhost:3000/ping

###

POST http://localhost:3000/todos HTTP/1.1
content-type: application/json

{
  "title": "sample"
}

###

POST http://localhost:3000/todos HTTP/1.1
content-type: application/json

{ }

###

POST http://localhost:3000/no-existed-path HTTP/1.1
content-type: application/json


###

GET  http://localhost:3000/todos/
###

GET  http://localhost:3000/todos/61aa42a5d438a5669c7b7971


###

GET  http://localhost:3000/todos/61aa3b1f0443008788bcf6ddinvalidid

###

GET  http://localhost:3000/todos/61aa3b5dee222f3688bf8efa

###

PUT http://localhost:3000/todos/61aa42a5d438a5669c7b7971 HTTP/1.1
content-type: application/json

{
  "title": "dated title"
}

###

PUT http://localhost:3000/todos/61aa3b5dee222f3688bf8efa HTTP/1.1
content-type: application/json

{
  "title": "dated title"
}
